To be written


@node Numerical integration References and Further Reading
@section Numerical integration  References and Further Reading

@noindent
The complete story of QUADPACK is given in the book of the same name
written by the original developers. It describes the algorithms used in
QUADPACK and includes test programs, examples and useful advice on
numerical integration. It also has many references to the numerical
integration literature.

@itemize @asis
@item
R. Piessens, E. de Doncker-Kapenga, C.W. Uberhuber, D.K. Kahaner.
@cite{@sc{QUADPACK} A subroutine package for automatic integration}
Springer Verlag, 1983.
@end itemize
@noindent

