This chapter describes functions for solving polynomials.

@menu
* Quadratic equations::         
* Cubic equations::             
@end menu


@node  Quadratic equations
@section Quadratic equations

@deftypefun int gsl_poly_solve_quadratic (double @var{a}, double @var{b}, double @var{c}, double *@var{x0}, double *@var{x1})
This function solves the quadratic equation

@tex
\beforedisplay
$$
a x^2 + b x + c = 0
$$
\afterdisplay
@end tex
@ifinfo
@example
a x^2 + b x + c = 0
@end example
@end ifinfo

@noindent

@end deftypefun

@deftypefun int gsl_poly_complex_solve_quadratic (double @var{a}, double @var{b}, double @var{c}, gsl_complex *@var{z0}, gsl_complex *@var{z1})
@end deftypefun


@node Cubic equations
@section Cubic equations

@deftypefun int gsl_poly_solve_cubic (double @var{a}, double @var{b}, double @var{c}, double *@var{x0}, double *@var{x1}, double *@var{x2})
@end deftypefun

@deftypefun int gsl_poly_complex_solve_cubic (double @var{a}, double @var{b}, double @var{c}, gsl_complex *@var{z0}, gsl_complex *@var{x1}, gsl_complex *@var{z2})
@end deftypefun

