@comment
@node Dilogarithm
@section Dilogarithm
@cindex dilogarithm


@subsection Real Argument

In Lewin's notation this is @math{ Li_2(x) },
the real part of the dilogarithm of a real x.
It is defined by the integral representation
@math{ Li_2(x) = - Re \int_0^x ds \log(1-s) / s }.
Note that
@math{ Im Li_2(x) = ( 0 for x <= 1, -Pi*log(x) for x > 1 ) }.

@deftypefun  int gsl_sf_dilog_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_dilog_e(double x, gsl_sf_result * result)
@end deftypefun



@subsection Complex Argument

This is the full complex-valued dilogarithm for complex argument.
The argument is @math{ z = r \exp(i theta) }.

@deftypefun  int gsl_sf_complex_dilog_impl(double r, double theta, gsl_sf_result * result_re, gsl_sf_result * result_im)
@deftypefunx int gsl_sf_complex_dilog_e(double r, double theta, gsl_sf_result * result_re, gsl_sf_result * result_im)
@end deftypefun
