@comment
@node Logarithm and Related Functions
@section Logarithm and Related Functions
@cindex logarithm


@deftypefun double gsl_sf_log (double @var{x})
@deftypefunx int gsl_sf_log_e (double @var{x}, gsl_sf_result * @var{result})
Domain: x > 0.0 
@comment Exceptional Return Values: GSL_EDOM
@end deftypefun


@deftypefun double gsl_sf_log_abs (double @var{x})
@deftypefunx int gsl_sf_log_abs_e (double @var{x}, gsl_sf_result * @var{result})
\log(|x|) 
Domain: x != 0.0 
@comment Exceptional Return Values: GSL_EDOM
@end deftypefun


@deftypefun int gsl_sf_complex_log_e (double @var{zr}, double @var{zi}, gsl_sf_result * @var{lnr}, gsl_sf_result * @var{theta})
Complex Logarithm
  exp(lnr + I theta) = zr + I zi
Returns argument in [-pi,pi].
@comment Exceptional Return Values: GSL_EDOM
@end deftypefun


@deftypefun double gsl_sf_log_1plusx (double @var{x})
@deftypefunx int gsl_sf_log_1plusx_e (double @var{x}, gsl_sf_result * @var{result})
\log(1 + x) 
Domain: x > -1.0 
@comment Exceptional Return Values: GSL_EDOM
@end deftypefun


@deftypefun double gsl_sf_log_1plusx_mx (double @var{x})
@deftypefunx int gsl_sf_log_1plusx_mx_e (double @var{x}, gsl_sf_result * @var{result})
\log(1 + x) - x  
Domain: x > -1.0 
@comment Exceptional Return Values: GSL_EDOM
@end deftypefun
