@comment
@node Psi (Digamma) Function
@section Psi (Digamma) Function
@cindex psi function
@cindex digamma function
@cindex polygamma functions


The poly-gamma functions are defined by
@math{ psi(m,x) = (d/dx)^m psi(0,x) = (d/dx)^(m+1) log(gamma(x)) },
where @math{ \psi(0,x) } is called the di-gamma function.


@subsection Digamma Function

@deftypefun double gsl_sf_psi_int (int @var{n})
@deftypefunx int gsl_sf_psi_int_e (int @var{n}, gsl_sf_result * @var{result})
Domain: n integer, n > 0
@comment Exceptional Return Values: GSL_EDOM
@end deftypefun


@deftypefun double gsl_sf_psi (double @var{x})
@deftypefunx int gsl_sf_psi_e (double @var{x}, gsl_sf_result * @var{result})
Domain: x != 0.0
@comment Exceptional Return Values: GSL_EDOM, GSL_ELOSS
@end deftypefun


@deftypefun double gsl_sf_psi_1piy (double @var{y})
@deftypefunx int gsl_sf_psi_1piy_e (double @var{y}, gsl_sf_result * @var{result})
Di-Gamma Function Re[psi(1 + I y)]

exceptions: none

Computes @math{ Re psi(1 + I y) }.
@comment Exceptional Return Values: none
@end deftypefun


@subsection Trigamma Function

@deftypefun double gsl_sf_psi_1_int (int @var{n})
@deftypefunx int gsl_sf_psi_1_int_e (int @var{n}, gsl_sf_result * @var{result})
Domain: n integer, n > 0
@comment Exceptional Return Values: GSL_EDOM
@end deftypefun


@subsection Polygamma Function

@deftypefun double gsl_sf_psi_n (int @var{m}, double @var{x})
@deftypefunx int gsl_sf_psi_n_e (int @var{m}, double @var{x}, gsl_sf_result * @var{result})
Domain: m >= 0, x > 0.0
@comment Exceptional Return Values: GSL_EDOM
@end deftypefun
