@comment
@node Exponential Integrals
@section Exponential Integrals
@cindex exponential integrals


@subsection Exponential Integrals

We have
@math{ E_1(x) := Re \int_1^\infty dt \exp(-xt)/t };
@math{ E_2(x) := Re \int_1^\infty dt \exp(-xt)/t^2 }.

@deftypefun double gsl_sf_expint_E1 (double @var{x})
@deftypefunx int gsl_sf_expint_E1_e (double @var{x}, gsl_sf_result * @var{result})
Domain: x != 0.0
@comment Exceptional Return Values: GSL_EDOM, GSL_EOVRFLW, GSL_EUNDRFLW
@end deftypefun


@deftypefun double gsl_sf_expint_E2 (double @var{x})
@deftypefunx int gsl_sf_expint_E2_e (double @var{x}, gsl_sf_result * @var{result})
Domain: x != 0.0
@comment Exceptional Return Values: GSL_EDOM, GSL_EOVRFLW, GSL_EUNDRFLW
@end deftypefun



@subsection Ei(x)

We have
@math{ Ei(x) := PV \int_(-x)^\infty dt \exp(-t)/t }.

@deftypefun double gsl_sf_expint_Ei (double @var{x})
@deftypefunx int gsl_sf_expint_Ei_e (double @var{x}, gsl_sf_result * @var{result})
Domain: x != 0.0
@comment Exceptional Return Values: GSL_EDOM, GSL_EOVRFLW, GSL_EUNDRFLW
@end deftypefun


@subsection Hyperbolic Integrals

We have
@math{ Shi(x) = \int_0^x dt \sinh(t)/t };
@math{ Chi(x) := Re[ M_EULER + log(x) + \int_0^x dt (Cosh[t]-1)/t }.


@deftypefun double gsl_sf_Shi (double @var{x})
@deftypefunx int gsl_sf_Shi_e (double @var{x}, gsl_sf_result * @var{result})
@comment Exceptional Return Values: GSL_EOVRFLW, GSL_EUNDRFLW
@end deftypefun


@deftypefun double gsl_sf_Chi (double @var{x})
@deftypefunx int gsl_sf_Chi_e (double @var{x}, gsl_sf_result * @var{result})
Domain: x != 0.0
@comment Exceptional Return Values: GSL_EDOM, GSL_EOVRFLW, GSL_EUNDRFLW
@end deftypefun


@subsection Ei_3(x)

We have
@math{ Ei_3(x) = \int_0^x dt \exp(-t^3) }.

@deftypefun double gsl_sf_expint_3 (double @var{x})
@deftypefunx int gsl_sf_expint_3_e (double @var{x}, gsl_sf_result * @var{result})
Domain: x >= 0.0
@comment Exceptional Return Values: GSL_EDOM
@end deftypefun



@subsection Trigonometric Integrals

We have
@math{ Si(x) = \int_0^x dt \sin(t)/t };
@math{ Ci(x) = -\int_x^\infty \cos(t)/t }.


@deftypefun double gsl_sf_Si (const double @var{x})
@deftypefunx int gsl_sf_Si_e (double @var{x}, gsl_sf_result * @var{result})
@comment Exceptional Return Values: none
@end deftypefun

 
@deftypefun double gsl_sf_Ci (const double @var{x})
@deftypefunx int gsl_sf_Ci_e (double @var{x}, gsl_sf_result * @var{result})
Domain: x > 0.0
@comment Exceptional Return Values: GSL_EDOM
@end deftypefun


@subsection Arctangent Integral

We have
@math{ AtanInt(x) = \int_0^x dt \arctan(t)/t }.

@deftypefun double gsl_sf_atanint (double @var{x})
@deftypefunx int gsl_sf_atanint_e (double @var{x}, gsl_sf_result * @var{result})
Domain: 
@comment Exceptional Return Values: 
@end deftypefun
