@comment
@node Error Function
@section Error Function
@cindex error function
@cindex erf(x)
@cindex erfc(x)


@subsection Complementary Error Function

We have
@math{ erfc(x) = 2/\sqrt(Pi) \int_x^\infty \exp(-t^2) }.

@deftypefun double gsl_sf_erfc (double @var{x})
@deftypefunx int gsl_sf_erfc_e (double @var{x}, gsl_sf_result * @var{result})
@comment Exceptional Return Values: none
@end deftypefun


@subsection Log Complementary Error Function

@deftypefun double gsl_sf_log_erfc (double @var{x})
@deftypefunx int gsl_sf_log_erfc_e (double @var{x}, gsl_sf_result * @var{result})
@comment Exceptional Return Values: none
@end deftypefun


@subsection Error Function
We have
@math{ erf(x) = 2/\sqrt(Pi) \int_0^x dt \exp(-t^2) }.

@deftypefun double gsl_sf_erf (double @var{x})
@deftypefunx int gsl_sf_erf_e (double @var{x}, gsl_sf_result * @var{result})
@comment Exceptional Return Values: none
@end deftypefun


@subsection Probability functions

Z(x) :  Abramowitz+Stegun 26.2.1
Q(x) :  Abramowitz+Stegun 26.2.3

@deftypefun double gsl_sf_erf_Z (double @var{x})
@deftypefunx double gsl_sf_erf_Q (double @var{x})
@deftypefunx int gsl_sf_erf_Z_e (double @var{x}, gsl_sf_result * @var{result})
@deftypefunx int gsl_sf_erf_Q_e (double @var{x}, gsl_sf_result * @var{result})
@comment Exceptional Return Values: none
@end deftypefun
