@comment
@node Laguerre Functions
@section Laguerre Functions
@cindex Laguerre functions
@cindex confluent hypergeometric function


The Laguerre polynomials are defined in terms of confluent
hypergeometric functions as
@math{ L^a_n(x) = (a+1)_n / n! 1F1(-n,a+1,x) }.


@deftypefun  int gsl_sf_laguerre_1_impl (double a, double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_laguerre_2_impl (double a, double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_laguerre_3_impl (double a, double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_laguerre_1_e (double a, double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_laguerre_2_e (double a, double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_laguerre_3_e (double a, double x, gsl_sf_result * result)
Evaluate generalized Laguerre polynomials using explicit representations.
Exceptional Return Values: none
@end deftypefun


@deftypefun  int gsl_sf_laguerre_n_impl (const int n, const double a, const double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_laguerre_n_e (int n, double a, double x, gsl_sf_result * result)
Domain: a > -1.0, n >= 0
Evaluate generalized Laguerre polynomials.
Exceptional Return Values: GSL_EDOM
@end deftypefun
