@comment
@node Zeta Functions
@section Zeta Functions
@cindex Zeta functions


@subsection Riemann Zeta Function

The Riemann zeta function is defined by
@tex
\beforedisplay
$$
\zeta(s) = \sum_{k=1}^\infty k^{-s}.
$$
\afterdisplay
@end tex


@deftypefun  int gsl_sf_zeta_int_impl(int n, gsl_sf_result * result)
@deftypefunx int gsl_sf_zeta_int_e(int n, gsl_sf_result * result)
Domain: n integer, n != 1
Exceptional Return Values: GSL_EDOM, GSL_EOVRFLW
@end deftypefun


@deftypefun  int gsl_sf_zeta_impl(double s, gsl_sf_result * result)
@deftypefunx int gsl_sf_zeta_e(double s, gsl_sf_result * result)
Domain: s != 1.0
Exceptional Return Values: GSL_EDOM, GSL_EOVRFLW
@end deftypefun



@subsection Hurwicz Zeta Function


The Hurwicz zeta function is defined by
@math{ zeta(s,q) = \sum_0^\infty (k+q)^(-s) }.

@deftypefun  int gsl_sf_hzeta_impl(double s, double q, gsl_sf_result * result)
@deftypefunx int gsl_sf_hzeta_e(double s, double q, gsl_sf_result * result)
Domain: s > 1.0, q > 0.0
Exceptional Return Values: GSL_EDOM, GSL_EUNDRFLW, GSL_EOVRFLW
@end deftypefun


@subsection Eta Function

The eta function is defined by
@math{ \eta(s) = (1-2^(1-s)) zeta(s) }.

@deftypefun  int gsl_sf_eta_int_impl(int n, gsl_sf_result * result)
@deftypefunx int gsl_sf_eta_int_e(int n, gsl_sf_result * result)
Exceptional Return Values: GSL_EUNDRFLW, GSL_EOVRFLW
@end deftypefun

@deftypefun  int gsl_sf_eta_impl(double s, gsl_sf_result * result)
@deftypefunx int gsl_sf_eta_e(double s, gsl_sf_result * result)
Exceptional Return Values: GSL_EUNDRFLW, GSL_EOVRFLW
@end deftypefun
