@comment
@node Elementary Operations
@section Elementary Operations
@cindex elementary operations
@cindex multiplication


@deftypefun  int gsl_sf_multiply_impl(double x, double y, gsl_sf_result * result)
@deftypefunx int gsl_sf_multiply_e(double x, double y, gsl_sf_result * result)
Multiplication.
Exceptional Return Values: GSL_EOVRFLW, GSL_EUNDRFLW
@end deftypefun


@deftypefun  int gsl_sf_multiply_err_impl(double x, double dx, double y, double dy, gsl_sf_result * result)
@deftypefunx int gsl_sf_multiply_err_e(double x, double dx, double y, double dy, gsl_sf_result * result)
Multiplication of quantities with associated errors.
Exceptional Return Values: GSL_EOVRFLW, GSL_EUNDRFLW
@end deftypefun
