@comment
@node Error Function
@section Error Function
@cindex error function
@cindex erf(x)
@cindex erfc(x)


@subsection Complementary Error Function

We have
@math{ erfc(x) = 2/\sqrt(Pi) \int_x^\infty \exp(-t^2) }.

@deftypefun  int gsl_sf_erfc_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_erfc_e(double x, gsl_sf_result * result)
Exceptional Return Values: none
@end deftypefun


@subsection Log Complementary Error Function

@deftypefun  int gsl_sf_log_erfc_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_log_erfc_e(double x, gsl_sf_result * result)
Exceptional Return Values: none
@end deftypefun


@subsection Error Function
We have
@math{ erf(x) = 2/\sqrt(Pi) \int_0^x dt \exp(-t^2) }.

@deftypefun  int gsl_sf_erf_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_erf_e(double x, gsl_sf_result * result)
Exceptional Return Values: none
@end deftypefun


@subsection Probability functions

Z(x) :  Abramowitz+Stegun 26.2.1
Q(x) :  Abramowitz+Stegun 26.2.3

@deftypefun  int gsl_sf_erf_Z_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_erf_Q_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_erf_Z_e(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_erf_Q_e(double x, gsl_sf_result * result)
Exceptional Return Values: none
@end deftypefun
