@comment
@node Dawson Function
@section Dawson Function
@cindex Dawson function

The Dawson integral is defined by
@math{ \exp(-x^2) \int_0^x dt \exp(t^2) }.

@deftypefun  int gsl_sf_dawson_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_dawson_e(double x, gsl_sf_result * result)
Exceptional Return Values: GSL_EUNDRFLW
@end deftypefun
