@comment
@node Fermi-Dirac Function
@section Fermi-Dirac Function
@cindex Fermi-Dirac function



@subsection Complete Fermi-Dirac Integrals

F_j(x)   := 1/Gamma[j+1] Integral[ t^j /(Exp[t-x] + 1), (t,0,Infinity)]

@deftypefun double gsl_sf_fermi_dirac_m1 (double @var{x})
@deftypefunx int gsl_sf_fermi_dirac_m1_e (double @var{x}, gsl_sf_result * @var{result})
Complete integral F_(-1)(x) = e^x / (1 + e^x)
@comment Exceptional Return Values: GSL_EUNDRFLW
@end deftypefun

@deftypefun double gsl_sf_fermi_dirac_0 (double @var{x})
@deftypefunx int gsl_sf_fermi_dirac_0_e (double @var{x}, gsl_sf_result * @var{result})
Complete integral F_0(x) = ln(1 + e^x)
@comment Exceptional Return Values: GSL_EUNDRFLW
@end deftypefun

@deftypefun double gsl_sf_fermi_dirac_1 (double @var{x})
@deftypefunx int gsl_sf_fermi_dirac_1_e (double @var{x}, gsl_sf_result * @var{result})
Complete integral F_1(x)
@comment Exceptional Return Values: GSL_EUNDRFLW, GSL_EOVRFLW
@end deftypefun

@deftypefun double gsl_sf_fermi_dirac_2 (double @var{x})
@deftypefunx int gsl_sf_fermi_dirac_2_e (double @var{x}, gsl_sf_result * @var{result})
Complete integral F_2(x)
@comment Exceptional Return Values: GSL_EUNDRFLW, GSL_EOVRFLW
@end deftypefun

@deftypefun double gsl_sf_fermi_dirac_int (int @var{j}, double @var{x})
@deftypefunx int gsl_sf_fermi_dirac_int_e (int @var{j}, double @var{x}, gsl_sf_result * @var{result})
Complete integral F_j(x) for integer j
@comment Exceptional Return Values: GSL_EUNDRFLW, GSL_EOVRFLW
@end deftypefun

@deftypefun double gsl_sf_fermi_dirac_mhalf (double @var{x})
@deftypefunx int gsl_sf_fermi_dirac_mhalf_e (double @var{x}, gsl_sf_result * @var{result})
Complete integral F_(-1/2)(x)
@comment Exceptional Return Values: GSL_EUNDRFLW, GSL_EOVRFLW
@end deftypefun

@deftypefun double gsl_sf_fermi_dirac_half (double @var{x})
@deftypefunx int gsl_sf_fermi_dirac_half_e (double @var{x}, gsl_sf_result * @var{result})
Complete integral F_(1/2)(x)
@comment Exceptional Return Values: GSL_EUNDRFLW, GSL_EOVRFLW
@end deftypefun

@deftypefun double gsl_sf_fermi_dirac_3half (double @var{x})
@deftypefunx int gsl_sf_fermi_dirac_3half_e (double @var{x}, gsl_sf_result * @var{result})
Complete integral F_(3/2)(x)
@comment Exceptional Return Values: GSL_EUNDRFLW, GSL_EOVRFLW
@end deftypefun


@subsection Incomplete Fermi-Dirac Integrals:

F_j(x,b) := 1/Gamma[j+1] Integral[ t^j /(Exp[t-x] + 1), (t,b,Infinity)]

@deftypefun double gsl_sf_fermi_dirac_inc_0 (double @var{x}, double @var{b})
@deftypefunx int gsl_sf_fermi_dirac_inc_0_e (double @var{x}, double @var{b}, gsl_sf_result * @var{result})
Incomplete integral F_0(x,b) = ln(1 + e^(b-x)) - (b-x)
@comment Exceptional Return Values: GSL_EUNDRFLW, GSL_EDOM
@end deftypefun

