@comment
@node Dawson Function
@section Dawson Function
@cindex Dawson function

The Dawson integral is defined by
@math{ \exp(-x^2) \int_0^x dt \exp(t^2) }.

@deftypefun double gsl_sf_dawson (double @var{x})
@deftypefunx int gsl_sf_dawson_e (double @var{x}, gsl_sf_result * @var{result})
@comment Exceptional Return Values: GSL_EUNDRFLW
@end deftypefun
