@comment
@node Coupling Coefficients
@section Coupling Coefficients
@cindex 3j symbols
@cindex 6j symbols
@cindex 9j symbols
@cindex Wigner coefficients
@cindex Racah coefficients


Since the arguments of the standard coupling coefficient functions
are integer or half-integer, the arguments of the following functions
are by convention integers equal to twice the actual spin value.


@subsection 3j Symbols

@multitable {abc} {abc} {abc}
@item ja @tab jb @tab jc
@item ma @tab mb @tab mc
@end multitable

@deftypefun  int gsl_sf_coupling_3j_impl (
  int two_ja, int two_jb, int two_jc, 
  int two_ma, int two_mb, int two_mc, 
  gsl_sf_result * result)
@deftypefunx int gsl_sf_coupling_3j_e (
  int two_ja, int two_jb, int two_jc, 
  int two_ma, int two_mb, int two_mc, 
  gsl_sf_result * result) 
Exceptional Return Values: GSL_EDOM, GSL_EOVRFLW
@end deftypefun



@subsection 6j Symbols

@multitable {abc} {abc} {abc}
@item ja @tab jb @tab jc
@item jd @tab je @tab jf
@end multitable

@deftypefun  int gsl_sf_coupling_6j_impl (
  int two_ja, int two_jb, int two_jc, 
  int two_jd, int two_je, int two_jf, 
  gsl_sf_result * result)
@deftypefunx int gsl_sf_coupling_6j_e (
  int two_ja, int two_jb, int two_jc, 
  int two_jd, int two_je, int two_jf, 
  gsl_sf_result * result) 
Exceptional Return Values: GSL_EDOM, GSL_EOVRFLW
@end deftypefun



@subsection 9j Symbols

@multitable {abc} {abc} {abc}
@item ja @tab jb @tab jc
@item jd @tab je @tab jf
@item jg @tab jh @tab ji
@end multitable

@deftypefun  int gsl_sf_coupling_9j_impl (
  int two_ja, int two_jb, int two_jc, 
  int two_jd, int two_je, int two_jf, 
  int two_jg, int two_jh, int two_ji, 
  gsl_sf_result * result)
@deftypefunx int gsl_sf_coupling_9j_e (
  int two_ja, int two_jb, int two_jc, 
  int two_jd, int two_je, int two_jf, 
  int two_jg, int two_jh, int two_ji, 
  gsl_sf_result * result) 
Exceptional Return Values: GSL_EDOM, GSL_EOVRFLW
@end deftypefun
