@comment
@node Elliptic Functions (Jacobi)
@section Elliptic Functions (Jacobi)
@cindex elliptic functions (Jacobi)


@deftypefun int gsl_sf_elljac_e (double @var{u}, double @var{m}, double * @var{sn}, double * @var{cn}, double * @var{dn})
Jacobian elliptic functions sn, dn, cn,
calculated by descending Landen transformations.
@comment Exceptional Return Values: GSL_EDOM
@end deftypefun
