@comment
@node Clausen Functions
@section Clausen Functions
@cindex Clausen functions


The Clausen integral is defined to be
@math{ Cl_2(x) = - \int_0^x dt \log(2 \sin(t/2)) }.

It is related to the dilogarithm by
@math{ Cl_2(theta) = Im  Li_2(\exp(i theta)) }.


@deftypefun  int gsl_sf_clausen_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_clausen_e(double x, gsl_sf_result * result)
@end deftypefun
