@comment
@node Polynomial Manipulation
@section Polynomial Manipulation
@cindex polynomial manipulation

@deftypefun double gsl_sf_poly_eval (const double c[], const int @var{len}, const double @var{x})
This function evaluates the polynomial @math{c[0] + c[1] x + c[2] x^2 +
\dots + c[len-1] x^(len-1)}.
@comment Exceptional Return Values: none
@end deftypefun
