@comment
@node Debye Functions
@section Debye Functions
@cindex Debye functions

The Debye integrals are defined by
@math{ D_n(x) = n/x^n \int_0^x dt t^n/(e^t - 1) }.


@deftypefun  int gsl_sf_debye_1_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_debye_1_e(double x, gsl_sf_result * result)
Exceptional Return Values: GSL_EDOM
@end deftypefun

@deftypefun  int gsl_sf_debye_2_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_debye_2_e(double x, gsl_sf_result * result)
Exceptional Return Values: GSL_EDOM, GSL_EUNDRFLW
@end deftypefun

@deftypefun  int gsl_sf_debye_3_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_debye_3_e(double x, gsl_sf_result * result)
Exceptional Return Values: GSL_EDOM, GSL_EUNDRFLW
@end deftypefun

@deftypefun  int gsl_sf_debye_4_impl(double x, gsl_sf_result * result)
@deftypefunx int gsl_sf_debye_4_e(double x, gsl_sf_result * result)
Exceptional Return Values: GSL_EDOM, GSL_EUNDRFLW
@end deftypefun
