#! /bin/sh
## Bugs: too clever by half!
## But still not clever enough, since auxlist has to be
## specified here, and not on the command line


list="$*"
auxlist=""
auxbin="test-switch"

echo -n "noinst_PROGRAMS= "     # don't want to install tests globally
for i in $list $auxlist; do
    echo -n "$i test-$i bench-$i "
done
echo -n "$auxbin "
echo ""
echo ""

echo -n "TESTS = "
for i in $list $auxlist; do
    echo -n "test-$i "
done
echo ""
echo ""

echo -n "lib_LIBRARIES= libgslrandom.a "
for i in $list; do
    echo -n "libgslran$i.a "
done
echo ""
echo ""
for i in $list; do
    echo "libgslran${i}_a_SOURCES= $i.c $i-gen.c "
done
echo ""

echo -n "libgslrandom_a_SOURCES= switch.c "
for i in $list $auxlist; do
    echo -n "$i.c "
done
echo ""
echo ""

echo -n "test_switch_DEPENDENCIES= gsl_ran_switch.h "
for i in $list; do
    echo -n "$i.h $i.o "
done
echo ""

echo -n "test_switch_LDADD= "
for i in $list; do
    echo -n "$i.o "
done
echo ""
    
for i in $list; do
    echo "${i}_SOURCES=             ran.c $i.c"
    echo "${i}_DEPENDENCIES=        $i-state.c $i.h $i-gen.o"
    echo "${i}_LDADD=               $i-gen.o"
    echo "test_${i}_SOURCES=        testran.c"
    echo "test_${i}_DEPENDENCIES=   $i.o $i-gen.o $i.h"
    echo "test_${i}_LDADD=          $i.o $i-gen.o ../err/libgsltest.a ../utils/libutils.a"
    echo "bench_${i}_SOURCES=       benchran.c"
    echo "bench_${i}_DEPENDENCIES=  $i.o $i-gen.o $i.h"
    echo "bench_${i}_LDADD=         $i.o $i-gen.o"
done
echo ""

for i in $list; do
    echo "$i-state.c: xxx-state.xc"
    echo "	sed s/gsl_ran_XXX_/gsl_ran_${i}_/g xxx-state.xc > \$@"
    echo "$i.h: gsl_ran.h"
    echo "	sed s/gsl_ran_/gsl_ran_${i}_/g gsl_ran.h > \$@"
    echo "$i-gen.c: xxx-gen.xc"
    echo "	sed s/XXX/$i/g xxx-gen.xc > \$@"
done
echo ""

echo -n "BUILT_SOURCES= "
for i in $list; do
    echo -n "$i.h $i-state.c $i-gen.c "
done
echo -n "gsl_ran_switch.h switch.c"

##
