#! /bin/sh 
## $Id$
## Convert template switch.xc to actual switch.c/gsl_ran_switch.h
## source code by replacing xxx section with specific mrg, crmg, etc.

fave=$1
list=$*

echo "void gsl_ran_use_default(void);" >> gsl_ran_switch.h
for xxx in $list; do
    echo "void gsl_ran_use_$xxx(void);" >> gsl_ran_switch.h
done

sed -n -e '/include..xxx.h./,$p' < switch.xc > tmp.xxx
sed    -e '/include..xxx.h./,$d' \
       -e s/yyy/$fave/           < switch.xc > switch.c

for xxx in $list; do
    sed s/xxx/$xxx/g tmp.xxx >> switch.c
done

/bin/rm tmp.xxx

##




