#! /bin/sh
## $Id$
## Usage: 'makeam [Makefile.ami] > Makefile.am'
## makes the 'Makefile.am' file from the template 'Makefile.ami'

ami=Makefile.ami
if [ $# -gt 0 ]; then
    ami=$1
fi

list=`egrep '^ALLRAN=' $ami | sed s/ALLRAN=//`

first () { echo $1 }
fave=`first $list`

##################################################
## Start writing the Makefile.am
##
echo '### $Id$' 
cat Makefile.ami   | egrep -v '^### '
echo FAVORITERAN= $fave
    
auxbin="test-switch"

echo -n "bin_PROGRAMS= "
for i in $list; do
    echo -n "$i test-$i bench-$i "
done
echo -n "$auxbin "
echo ""
echo ""

echo -n "lib_LIBRARIES= libgslrandom.a "
for i in $list; do
    echo -n "libgslran$i.a "
done
echo ""
echo ""
for i in $list; do
    echo "libgslran${i}_a_SOURCES= $i.c $i-gen.c "
done
echo ""

echo -n "libgslrandom_a_SOURCES= switch.c "
for i in $list; do
    echo -n "$i.c "
done
echo ""
echo ""

echo -n "test_switch_DEPENDENCIES= gsl_ran_switch.h "
for i in $list; do
    echo -n "$i.h $i.o "
done
echo ""

echo -n "test_switch_LDADD= "
for i in $list; do
    echo -n "$i.o "
done
echo ""
    
    for i in $list; do
    echo "${i}_SOURCES=             ran.c $i.c"
    echo "${i}_DEPENDENCIES=        $i-state.c $i.h $i-gen.o"
    echo "${i}_LDADD=               $i-gen.o"
    echo "test_${i}_SOURCES=        testran.c"
    echo "test_${i}_DEPENDENCIES=   $i.o $i-gen.o $i.h"
    echo "test_${i}_LDADD=          $i.o $i-gen.o"
    echo "bench_${i}_SOURCES=       benchran.c"
    echo "bench_${i}_DEPENDENCIES=  $i.o $i-gen.o $i.h"
    echo "bench_${i}_LDADD=         $i.o $i-gen.o"
done
echo ""

echo "## Note, BUILT_SOURCES has special meaning to automake"
echo "## I'm deliberately trying to avoid having the casual user"
echo "## build sources.  If you want to build THE_BUILT_SOURCESS"
echo "## then run the program './makesrc'"
echo -n "THE_BUILT_SOURCES= "
for i in $list; do
    echo -n "$i.h $i-state.c $i-gen.c "
done
echo -n "gsl_ran_switch.h switch.c"
echo ""
echo "## If you need to build these sources, use the 'makesrc' script"
for i in $list; do
    echo "$i.h $i-state.c $i-gen.c: makesrc"
    echo "	./makesrc $i"
    echo ""
done

echo "## This target is kind of like 'distclean'"
echo "tooclean:"
echo "	/bin/rm -rf .deps"
for i in $list; do
    echo "	/bin/rm -f $i.h $i-state.c $i-gen.c"
done
echo "	/bin/rm switch.c gsl_ran_switch.h"
echo ""
     
##




